# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Virtually an Admin
tagline:          Administrating in the Clouds
url:              http://virtuallyanadmin.com
baseurl:          /

author:
  name:           'Jonathan Stewart'
  url:            https://twitter.com/virtuallyanadmin

paginate:         5
paginate_path:    "page/:num"

jekyll_timeago:
  depth:          1
  suffix:         'old'

assets:
  js_compressor:  uglifier
  css_compressor: sass

exclude: [rakefile.rb, CNAME, LICENSE.md, README.md]
